# Docker compose for bringing up Schema Registry while hiding the JAAS credendtials in a docker var.

---
version: '2'
services:
  schema-registry:
    container_name: schema-registry
    ports:
      - "8081:8081"
    image:  confluentinc/cp-schema-registry:latest  
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: $JAAS
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: pkc-lgwgm.eastus2.azure.confluent.cloud:9092
      SCHEMA_REGISTRY_KAFKASTORE_SASL_MECHANISM: PLAIN
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SASL_SSL
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas_ext1_
      SCHEMA_REGISTRY_KAFKASTORE_GROUP_ID: ptr_vdev_schema_registry_1_
      SCHEMA_REGISTRY_SCHEMA_REGISTRY_GROUP_ID: ptr_vdev_schema_registry_1_

